import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          !DEVOPS CRASH COURSE!
        </h1>

        <div className={styles.grid}>
          <a href="https://www.softserveinc.com/en-us/" className={styles.card}>
            <h2>SoftServe</h2>
            <p>Find in-depth information about SoftServe</p>
          </a>

          <a href="https://malcak.me" className={styles.card}>
            <h2>Malcak</h2>
            <p>More information about me :D</p>
          </a>

          <a
            href="https://www.jenkins.io/doc/book/installing/"
            className={styles.card}
          >
            <h2>Jenkins</h2>
            <p>Find more about Jenkins in Jenkins&apos;s documentation</p>
          </a>

          <a
            href="https://docs.docker.com/"
            className={styles.card}
          >
            <h2>Docker</h2>
            <p>
              Find more about Docker in Docker&apos;s documentation
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
